[package]
name = "BTree"
version = "0.1.0"
authors = ["Charles VUILLECARD <charles.vuillec@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam= "0.8.1"
crossbeam-channel="0.5.1"
